<a href="https://colab.research.google.com/github/SparkyGoLarky/SparkyGoLarky/blob/main/Numpy_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#np arrays
x_values = [1,4,5,3,3,5,7,3,5,6]
numpy_x_values = np.array(x_values)
print(x_values)
print(type(x_values))
print(numpy_x_values)
print(type(numpy_x_values))

[1, 4, 5, 3, 3, 5, 7, 3, 5, 6]
<class 'list'>
[1 4 5 3 3 5 7 3 5 6]
<class 'numpy.ndarray'>


In [ ]:
#0 & 1 arrays
ones_array = np.ones(10, dtype=int)
print(ones_array)
zeros_array = np.zeros(5, dtype=int)
print(zeros_array)
empty_array = np.empty(4, dtype=int)
print(empty_array)

[1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0]
[1 1 1 0]


In [ ]:
#np range arrays
range_array = np.arange(10)
print(range_array)
range_array = np.arange(10, 21)
print(range_array)
range_array = np.arange(10, 101, 10)
print(range_array)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19 20]
[ 10  20  30  40  50  60  70  80  90 100]


In [ ]:
#linspace array
linspace_array = np.linspace(1, 10, 5)
print(linspace_array)
linspace_array = np.linspace(1, 100, 5)
print(linspace_array)
linspace_array = np.linspace(250, 1750, 10)
print(linspace_array)

[ 1.    3.25  5.5   7.75 10.  ]
[  1.    25.75  50.5   75.25 100.  ]
[ 250.          416.66666667  583.33333333  750.          916.66666667
 1083.33333333 1250.         1416.66666667 1583.33333333 1750.        ]


In [ ]:
#np matrices
matrix = [[1,2,3], [4,5,6], [7,8,9]]
numpy_matrix = np.array(matrix)
print(matrix)
print(numpy_matrix)
print(np.array([[[1,2],[3,4]],[[5,6],[7,8]]]))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
zeros_array = np.zeros((2, 3))
print(zeros_array)
ones_array = np.ones((3, 2))
print(ones_array)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#reshape
some_array = np.array([1,2,3,4,5,6])
reshaped_array = some_array.reshape(2,3)
print(reshaped_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
#function matrix creation
def f(r, c):
  return r*c
some_matrix = np.fromfunction(f,(3,3))
print(some_matrix)

[[0. 0. 0.]
 [0. 1. 2.]
 [0. 2. 4.]]


In [ ]:
range_array = np.arange(10).reshape(2,5)
print(range_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
#np elements
some_array = np.array([1,2,3,4,5,6,7,8,9,10])
print(some_array[0])
print(some_array[9])
some_array[9] = 11
print(some_array)

1
10
[ 1  2  3  4  5  6  7  8  9 11]


In [ ]:
some_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(some_matrix)
print(some_matrix[0])
print(some_matrix[0,2])
some_matrix[1,1] = 10
print(some_matrix)
some_matrix[2] = np.array([10,11,12])
print(some_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
3
[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]
[[ 1  2  3]
 [ 4 10  6]
 [10 11 12]]


In [ ]:
#slice
some_array = np.array([1,2,3,4,5,6,7,8,9,10])
print(some_array[0:5])
print(some_array[-1])
some_array[5:10] = 7
print(some_array)

[1 2 3 4 5]
10
[1 2 3 4 5 7 7 7 7 7]


In [ ]:
some_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(some_matrix[0,0:2])
print(some_matrix[:,1])
print(some_matrix[:,1:3])

[1 2]
[2 5 8]
[[2 3]
 [5 6]
 [8 9]]


In [ ]:
#arithmetic operations
some_array = np.array([1,2,3,4,5])
result = some_array * 2
print(result)
result = some_array + np.array([6,7,8,9,10])
print(result)
result = some_array[:3] + np.array([6,7,8])
print(result)

[ 2  4  6  8 10]
[ 7  9 11 13 15]
[ 7  9 11]


In [ ]:
some_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
result = some_matrix + 5
print(result)
result = some_matrix + np.array([[1,2,3],[4,5,6],[7,8,9]])
print(result)
result = some_matrix[0] + np.array([[1,2,3],[4,5,6],[7,8,9]])[0]
print(result)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[2 4 6]


In [ ]:
#dot product multiplication 
matrix_1 = np.array([[1,2,3],[4,5,6]])
matrix_2 = np.array([[7,8],[9,10],[11,12]])
result = matrix_1.dot(matrix_2)
print(result)
result = matrix_1 @ matrix_2
print(result)

[[ 58  64]
 [139 154]]
[[ 58  64]
 [139 154]]


In [ ]:
#np functions
#append
some_array = np.array([1,2,3])
result = np.append(some_array, 4)
print(result)
result = np.append(some_array, [4,5,6])
print(result)
result = np.append(some_array, [some_array, some_array])
print(result)

[1 2 3 4]
[1 2 3 4 5 6]
[1 2 3 1 2 3 1 2 3]


In [ ]:
#insert
some_array = np.array([1,2,3])
result = np.insert(some_array, 2, 5)
print(result)

[1 2 5 3]


In [ ]:
#delete
some_array = np.array([1,2,3])
result = np.delete(some_array, 0)
print(result)
result = np.delete(some_array, [0,1])
print(result)

[2 3]
[3]


In [ ]:
#applying to matrix - append
some_matrix = np.array([[1,2,3],[4,5,6]])
result = np.append(some_matrix, [[7,8,9]], 0)
print(result)
result = np.append(some_matrix, [[7],[8]], 1)
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 7]
 [4 5 6 8]]


In [ ]:
#insert
some_matrix = np.array([[1,2,3],[4,5,6]])
result = np.insert(some_matrix, 1, [7,8,9], 0)
print(result)
result = np.insert(some_matrix, 2, [7,8], 1)
print(result)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [ ]:
#delete
some_matrix = np.array([[1,2,3],[4,5,6]])
result = np.delete(some_matrix, 0, 0)
print(result)
result = np.delete(some_matrix, 1, 1)
print(result)

[[4 5 6]]


In [ ]:
matrix_1 = np.array([[7,3,5],[44,23,90],[2,20,40]])
result = np.append(matrix_1, [[4,5,22]], 0)
print(result)
result = np.insert(matrix_1, 1, [7,8,9], 0)
print(result)
result = np.delete(matrix_1, 0, 0)
print(result)

[[ 7  3  5]
 [44 23 90]
 [ 2 20 40]
 [ 4  5 22]]
[[ 7  3  5]
 [ 7  8  9]
 [44 23 90]
 [ 2 20 40]]
[[44 23 90]
 [ 2 20 40]]


In [ ]:
#fetch operations
some_array = np.array([4,0,6,1,2,3,0,5])
result = some_array.max()
print(result)
result = some_array.min()
print(result)
result = some_array.mean()
print(result)
result = some_array.argmax()
print(result)
result = some_array.argmin()
print(result)
result = some_array.nonzero()
print(result)

6
0
2.625
2
1
(array([0, 2, 3, 4, 5, 7]),)


In [ ]:
#modify operations
some_array = np.array([4,0,6,1,2,3,0,5])
some_array.sort()
print(some_array)
result = np.flip(some_array)
print(result)

[0 0 1 2 3 4 5 6]
[6 5 4 3 2 1 0 0]


In [ ]:
#matrix fetch
matrix_1 = np.array([[7,3,5],[44,23,90],[2,20,40]])
print(matrix_1)
result = matrix_1.max()
print(result)
result = matrix_1.max(0)
print(result)
result = matrix_1.argmax()
print(result)
result = matrix_1.argmax(0)
print(result)
result = matrix_1.argmax(1)
print(result)
result = matrix_1.argmin()
print(result)
result = matrix_1.argmin(0)
print(result)
result = matrix_1.argmin(1)
print(result)

[[ 7  3  5]
 [44 23 90]
 [ 2 20 40]]
90
[44 23 90]
5
[1 1 1]
[0 2 2]
6
[2 0 0]
[1 1 0]


In [ ]:
#matrix modify
matrix_1 = np.array([[7,3,5],[44,23,90],[2,20,40]])
matrix_1.sort()
print(matrix_1)
matrix_1.sort(0)
print(matrix_1)

[[ 3  5  7]
 [23 44 90]
 [ 2 20 40]]
[[ 2  5  7]
 [ 3 20 40]
 [23 44 90]]


In [ ]:
#transpose
matrix_1 = np.array([[7,3,5],[44,23,90]])
result = matrix_1.transpose()
print(result)
result = matrix_1.flatten()
print(result)

[[ 7 44]
 [ 3 23]
 [ 5 90]]
[ 7  3  5 44 23 90]
